oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    pattern:   /login
    defaults:  { _controller: OCUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
